-- Run this in Supabase SQL Editor.

-- 1) device_tokens hardening
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'device_tokens'
      and column_name = 'id'
      and is_identity = 'NO'
  ) then
    execute 'alter table public.device_tokens alter column id add generated by default as identity';
  end if;
end
$$;

alter table if exists public.device_tokens
  alter column "isActive" set default true,
  alter column "isAndroid" set default false,
  alter column "isArabic" set default false,
  alter column "lastSeen" set default now();

create index if not exists idx_device_tokens_userid
  on public.device_tokens("userID");

create index if not exists idx_device_tokens_active
  on public.device_tokens("isActive");

-- 2) Notification job queue consumed by your backend worker/edge function
create table if not exists public.notification_jobs (
  id bigserial primary key,
  "eventType" text not null,
  title text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  "isAndroidOnly" boolean not null default false,
  "isArabicOnly" boolean not null default false,
  status text not null default 'pending',
  attempts int not null default 0,
  "lastError" text,
  "lockedAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "processedAt" timestamptz
);

alter table if exists public.notification_jobs
  add column if not exists "lastError" text,
  add column if not exists "lockedAt" timestamptz;

create index if not exists idx_notification_jobs_status_created
  on public.notification_jobs(status, "createdAt");

create index if not exists idx_notification_jobs_status_locked
  on public.notification_jobs(status, "lockedAt");

-- 2.a) Claim pending jobs safely (for worker concurrency)
create or replace function public.claim_notification_jobs(p_limit int default 30)
returns setof public.notification_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.notification_jobs as j
  set status = 'processing',
      "lockedAt" = now(),
      attempts = j.attempts + 1
  where j.id in (
    select id
    from public.notification_jobs
    where status = 'pending'
    order by "createdAt" asc
    limit greatest(coalesce(p_limit, 30), 1)
    for update skip locked
  )
  returning j.*;
end;
$$;

-- 2.b) Mark a claimed job result
create or replace function public.complete_notification_job(
  p_job_id bigint,
  p_status text,
  p_last_error text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.notification_jobs
  set status = p_status,
      "lastError" = p_last_error,
      "processedAt" = now(),
      "lockedAt" = null
  where id = p_job_id;
end;
$$;

-- 3) Optional DB-level automation (in addition to app-side enqueue)
-- 3.a) Order status change -> queue notification job
create or replace function public.enqueue_order_status_notification()
returns trigger
language plpgsql
as $$
begin
  if new."orderStatus" is distinct from old."orderStatus" then
    insert into public.notification_jobs ("eventType", title, body, payload)
    values (
      'order_status_changed',
      format('Order #%s update', new.id),
      format('Your order is now: %s', new."orderStatus"),
      jsonb_build_object(
        'order_id', new.id,
        'status', new."orderStatus",
        'deep_link', format('/orders/%s', new.id)
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enqueue_order_status_notification on public.order_master;
create trigger trg_enqueue_order_status_notification
after update of "orderStatus" on public.order_master
for each row
execute function public.enqueue_order_status_notification();

-- 3.b) Newly featured item -> queue notification job
create or replace function public.enqueue_featured_item_notification()
returns trigger
language plpgsql
as $$
begin
  if new."isFeatured" = true and (tg_op = 'INSERT' or old."isFeatured" is distinct from new."isFeatured") then
    insert into public.notification_jobs ("eventType", title, body, payload)
    values (
      'featured_item_published',
      'Featured Item',
      format('Now featured: %s', new."itemName"),
      jsonb_build_object(
        'item_id', new.id,
        'deep_link', format('/item/%s', new.id)
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enqueue_featured_item_notification on public.items;
create trigger trg_enqueue_featured_item_notification
after insert or update of "isFeatured" on public.items
for each row
execute function public.enqueue_featured_item_notification();

-- 3.c) New promotion -> queue notification job
-- Assumes promotions has at least: id, promotionCode, promotionText.
create or replace function public.enqueue_promotion_notification()
returns trigger
language plpgsql
as $$
begin
  insert into public.notification_jobs ("eventType", title, body, payload)
  values (
    'promotion_published',
    coalesce(nullif(new."promotionText", ''), 'New Promotion'),
    format('Use code %s on your next order.', coalesce(new."promotionCode", '')), 
    jsonb_build_object(
      'promotion_id', new.id,
      'promotion_code', new."promotionCode",
      'deep_link', format('/home?promo=%s', coalesce(new."promotionCode", ''))
    )
  );

  return new;
end;
$$;

drop trigger if exists trg_enqueue_promotion_notification on public.promotions;
create trigger trg_enqueue_promotion_notification
after insert on public.promotions
for each row
execute function public.enqueue_promotion_notification();
