// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO96CpWCqCLnq2OefEpr39HTeRgvnRhR8',
    appId: '1:295714444020:web:6708072c5be0ea09b544a1',
    messagingSenderId: '295714444020',
    projectId: 'sora-eg',
    authDomain: 'sora-eg.firebaseapp.com',
    storageBucket: 'sora-eg.firebasestorage.app',
    measurementId: 'G-91GM5KYB5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbXd3lIV6zYpE6IWGRxcVrJ8C3Vx7CqFQ',
    appId: '1:295714444020:android:655c9e9ae0acdf8ab544a1',
    messagingSenderId: '295714444020',
    projectId: 'sora-eg',
    storageBucket: 'sora-eg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjPHeSnd6GvJv7iqUllrAkpAtM_r4I_p0',
    appId: '1:295714444020:ios:cc00a4ac92abe330b544a1',
    messagingSenderId: '295714444020',
    projectId: 'sora-eg',
    storageBucket: 'sora-eg.firebasestorage.app',
    iosBundleId: 'com.softforge.sora',
    iosClientId: '295714444020-hu37a175ntl53tn2jiubm1nesemv41d3.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjPHeSnd6GvJv7iqUllrAkpAtM_r4I_p0',
    appId: '1:295714444020:ios:cc00a4ac92abe330b544a1',
    messagingSenderId: '295714444020',
    projectId: 'sora-eg',
    storageBucket: 'sora-eg.firebasestorage.app',
    iosBundleId: 'com.softforge.sora',
    iosClientId: '295714444020-hu37a175ntl53tn2jiubm1nesemv41d3.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO96CpWCqCLnq2OefEpr39HTeRgvnRhR8',
    appId: '1:295714444020:web:7ab5befabf18d32ab544a1',
    messagingSenderId: '295714444020',
    projectId: 'sora-eg',
    authDomain: 'sora-eg.firebaseapp.com',
    storageBucket: 'sora-eg.firebasestorage.app',
    measurementId: 'G-HDKB2KEVBQ',
  );
}
